# This file was generated by GoReleaser. DO NOT EDIT.
cask "mace" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "b59a27537218b62c4580368521dde5880a66e6878ebfe1a5ca7b2f9609a37489"
      url "https://github.com/louiss0/mace/releases/download/v#{version}/mace_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4615b4562ed9b0124f2d1568079e4f114d207a2933b4fd9ca12ddca1af29f8aa"
      url "https://github.com/louiss0/mace/releases/download/v#{version}/mace_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b54f7745c7dbcc43f15a479e020c64e47324a5ef929830e5482904210fb01d90"
      url "https://github.com/louiss0/mace/releases/download/v#{version}/mace_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3d77e3aaea195c7eaf9d6bdd8183fde2a334af640c735bc8b844dddf0be2c98c"
      url "https://github.com/louiss0/mace/releases/download/v#{version}/mace_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mace"
  desc "Deterministic typed configuration language and Go toolkit."
  homepage "https://github.com/louiss0/mace"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mace"

  # No zap stanza required

end
