# This file was generated by GoReleaser. DO NOT EDIT.
cask "mace" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "b6183cb388be58f88fa8442fa6f322239b19ebea194ab621377c2f9da7366a3a"
      url "https://github.com/louiss0/mace/releases/download/v#{version}/mace_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "df9dd14658b70e735a23e0bc56ccd4f6e3a7ce8d59efd1dfb3b7f663363852ae"
      url "https://github.com/louiss0/mace/releases/download/v#{version}/mace_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ce9f05fd6f12f43233a38046305f857531b9e2f01e5233e7ef1e7fc4d1460abe"
      url "https://github.com/louiss0/mace/releases/download/v#{version}/mace_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dcb8c895ca142c5919b062ac89f17064cba28685788f5e9f40825997c2380464"
      url "https://github.com/louiss0/mace/releases/download/v#{version}/mace_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mace"
  desc "Deterministic typed configuration language and Go toolkit."
  homepage "https://github.com/louiss0/mace"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mace"

  # No zap stanza required

end
