# This file was generated by GoReleaser. DO NOT EDIT.
cask "mace" do
  name "mace"
  desc "Deterministic typed configuration language and Go toolkit."
  homepage "https://github.com/louiss0/mace"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mace"

  on_macos do
    on_intel do
      url "https://github.com/louiss0/mace/releases/download/v#{version}/mace_#{version}_darwin_amd64.tar.gz"
      sha256 "cd72afbe7a73f612680d518d1ee6c123a8e0a50e35215116cff42fc600452dc9"
    end
    on_arm do
      url "https://github.com/louiss0/mace/releases/download/v#{version}/mace_#{version}_darwin_arm64.tar.gz"
      sha256 "6ba9a5e8048a88a45d43d41f6aaedd58086aac9c09da34b64247ec52e30b9c48"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/louiss0/mace/releases/download/v#{version}/mace_#{version}_linux_amd64.tar.gz"
      sha256 "dfccccf3a5c0dff243ec5431b30a1f1e2ba40f95b4bac59149c6f4b36cded864"
    end
    on_arm do
      url "https://github.com/louiss0/mace/releases/download/v#{version}/mace_#{version}_linux_arm64.tar.gz"
      sha256 "f930fc8b1c2ded412bd6f2e3d4fda8807b2fabb96a6fe3efecaa131f9c56417a"
    end
  end

  # No zap stanza required
end
